plugins {
    id 'application'
    id 'java'
}

group = 'seedu.eventmanager'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.postgresql:postgresql:42.7.7'
    implementation 'org.flywaydb:flyway-core:11.11.2'
    implementation 'org.flywaydb:flyway-database-postgresql:11.11.2'

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'seedu.eventmanager.Main'
}

tasks.named('test') {
    useJUnitPlatform()
}
